"""Git worktree management for isolated slice execution."""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

log = logging.getLogger("jarvis.worktree_manager")

INTEGRATION_BRANCH = "integration"


def _run_git(*args: str, cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )


def init_project_repo(project_path: Path) -> Path:
    """Initialize git repo for a new build project."""
    project_path.mkdir(parents=True, exist_ok=True)
    if not (project_path / ".git").exists():
        _run_git("init", cwd=project_path)
        _run_git("config", "user.email", "william@jarvis.local", cwd=project_path)
        _run_git("config", "user.name", "William Agent", cwd=project_path)
        readme = project_path / "README.md"
        if not readme.is_file():
            readme.write_text("# Build project\n\nGenerated by William Agent build pipeline.\n", encoding="utf-8")
        _run_git("add", ".", cwd=project_path)
        _run_git("commit", "-m", "Initial project scaffold", cwd=project_path)
    branch = (_run_git("branch", "--show-current", cwd=project_path).stdout or "").strip()
    if not branch:
        _run_git("checkout", "-b", "main", cwd=project_path)
    if INTEGRATION_BRANCH not in (_run_git("branch", "--list", cwd=project_path).stdout or ""):
        _run_git("branch", INTEGRATION_BRANCH, cwd=project_path)
    return project_path


def create_worktree(
    project_path: Path,
    worktrees_dir: Path,
    slice_id: str,
    *,
    base_branch: str = "main",
) -> Path:
    """Create an isolated worktree for a slice branch."""
    worktrees_dir.mkdir(parents=True, exist_ok=True)
    branch = f"slice/{slice_id}"
    wt_path = worktrees_dir / slice_id

    if wt_path.is_dir() and (wt_path / ".git").exists():
        return wt_path

    if wt_path.exists():
        import shutil
        shutil.rmtree(wt_path, ignore_errors=True)

    _run_git("branch", "-f", branch, base_branch, cwd=project_path)
    result = _run_git(
        "worktree", "add", str(wt_path), branch,
        cwd=project_path,
    )
    if result.returncode != 0:
        log.warning("worktree add failed for %s: %s", slice_id, result.stderr)
        wt_path.mkdir(parents=True, exist_ok=True)
        init_project_repo(wt_path)
    return wt_path


def commit_worktree(worktree_path: Path, message: str) -> bool:
    if not (worktree_path / ".git").exists() and not (worktree_path / ".git").is_file():
        init_project_repo(worktree_path)
    _run_git("add", "-A", cwd=worktree_path)
    status = _run_git("status", "--porcelain", cwd=worktree_path)
    if not (status.stdout or "").strip():
        return True
    commit = _run_git("commit", "-m", message, cwd=worktree_path)
    return commit.returncode == 0


def merge_slice_to_integration(
    project_path: Path,
    slice_id: str,
) -> dict:
    """Merge slice branch into integration branch."""
    branch = f"slice/{slice_id}"
    checkout = _run_git("checkout", INTEGRATION_BRANCH, cwd=project_path)
    if checkout.returncode != 0:
        _run_git("checkout", "-b", INTEGRATION_BRANCH, cwd=project_path)
    merge = _run_git("merge", "--no-edit", branch, cwd=project_path)
    if merge.returncode != 0:
        return {
            "ok": False,
            "error": (merge.stderr or merge.stdout or "merge failed")[:500],
            "conflict": True,
        }
    return {"ok": True, "branch": branch}


def topological_order(slices: list[dict]) -> list[dict]:
    """Order slices by dependencies (foundations first)."""
    by_id = {sl["id"]: sl for sl in slices}
    ordered: list[dict] = []
    done: set[str] = set()

    def visit(sid: str) -> None:
        if sid in done or sid not in by_id:
            return
        sl = by_id[sid]
        for dep in sl.get("deps") or []:
            visit(dep)
        if sid not in done:
            ordered.append(sl)
            done.add(sid)

    for sl in sorted(slices, key=lambda s: s.get("ordinal", 0)):
        visit(sl["id"])
    return ordered


def ready_slices(slices: list[dict], completed: set[str]) -> list[dict]:
    """Slices whose dependencies are all completed."""
    ready: list[dict] = []
    for sl in slices:
        if sl.get("status") == "done":
            continue
        if sl.get("status") in ("running", "failed"):
            continue
        deps = set(sl.get("deps") or [])
        if deps <= completed:
            ready.append(sl)
    return ready
