#!/usr/bin/env bash
# Build staff-web for the waiter iPhone app with the Mac mini API URL baked in.
# Run on MacBook after cloning — Mac mini must have API running (pnpm dev:api).
#
# Usage:
#   ./scripts/prepare-waiter-ios.sh              # reads VITE_LAN_HOST from .env
#   ./scripts/prepare-waiter-ios.sh 10.43.0.40   # explicit Mac mini IP
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

IP="${1:-}"
if [[ -z "$IP" && -f .env ]]; then
  IP="$(grep -E '^VITE_LAN_HOST=' .env | cut -d= -f2- | tr -d ' \"' || true)"
fi

if [[ -z "$IP" ]]; then
  echo "Usage: $0 <MAC_MINI_LAN_IP>"
  echo "  Or set VITE_LAN_HOST in repo-root .env"
  echo "  On Mac mini run: ./scripts/print-network-urls.sh"
  exit 1
fi

ENV_FILE="apps/staff-web/.env.production"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/prepare-waiter-ios.sh — do not commit
VITE_API_BASE_URL=http://${IP}:3000/v1
VITE_LAN_HOST=${IP}
VITE_BASE_PATH=/
EOF

echo "==> Wrote $ENV_FILE"
echo "    API: http://${IP}:3000/v1"
echo ""

echo "==> Checking Mac mini API..."
if curl -sf "http://${IP}:3000/v1/health" >/dev/null; then
  echo "    API is reachable."
else
  echo "    WARNING: API not reachable at http://${IP}:3000/v1/health"
  echo "    On Mac mini: cd jarvis-core && pnpm dev:api"
  echo "    (or ./scripts/rekentafel-poc.sh)"
fi
echo ""

echo "==> Building staff-web + syncing Capacitor iOS..."
pnpm install
pnpm --filter @rekentafel/staff-web build

if xcodebuild -version >/dev/null 2>&1; then
  pnpm --filter @rekentafel/waiter-mobile cap:sync ios
else
  echo "    No full Xcode here — copying web assets only (run cap sync on MacBook)."
  pnpm --filter @rekentafel/waiter-mobile exec cap copy ios
fi

echo ""
echo "=============================================="
echo "  Ready for Xcode"
echo "=============================================="
echo ""
echo "  pnpm --filter @rekentafel/waiter-mobile cap:open:ios"
echo "  Select iPhone → Run (▶)"
echo ""
echo "  iPhone must be on the same Wi‑Fi as the Mac mini."
echo "=============================================="
