#!/usr/bin/env bash
# Write Vite env for guest-web so phones on venue Wi‑Fi hit the Mac mini API.
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

IP=""
for iface in en0 en1; do
  IP="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
  if [[ -n "$IP" ]]; then break; fi
done

if [[ -z "$IP" && -f .env ]]; then
  IP="$(grep -E '^VITE_LAN_HOST=' .env | cut -d= -f2- | tr -d ' \"' || true)"
fi

if [[ -z "$IP" ]]; then
  echo "Could not detect LAN IP. Pass it: $0 10.43.0.40"
  exit 1
fi

[[ -n "${1:-}" ]] && IP="$1"

GUEST_ENV="apps/guest-web/.env.local"
cat > "$GUEST_ENV" <<EOF
# Generated by scripts/write-guest-env.sh — do not commit
VITE_API_BASE_URL=http://${IP}:3000/v1
VITE_LAN_HOST=${IP}
EOF

if [[ -f .env ]]; then
  if grep -q '^VITE_LAN_HOST=' .env; then
    sed -i '' "s|^VITE_LAN_HOST=.*|VITE_LAN_HOST=${IP}|" .env
  else
    echo "VITE_LAN_HOST=${IP}" >> .env
  fi
fi

echo "Wrote ${GUEST_ENV}"
echo "  VITE_API_BASE_URL=http://${IP}:3000/v1"
echo ""
echo "Restart guest dev server: pnpm dev:guest"
echo "Or run everything:      ./scripts/rekentafel-poc.sh"
